import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/index.html');
  await page.getByRole('tab', { name: 'Codes, Hashes, Ciphers' }).click();
  await page.locator('textarea[name="inptxt"]').click();
  await page.locator('textarea[name="inptxt"]').fill('Dies ist ein beispielhafter schöner Testtext.');
  await page.locator('#nx-dropdown-rendered-0').click();
  await page.locator('#nx-dropdown-item-1').getByText('Utf8').click();
  await page.getByLabel('target encoding', { exact: true }).locator('svg').click();
  await page.getByRole('option').getByText('Base64').click();
  await page.getByRole('button', { name: 'Recode Text' }).click();
  await expect(page.locator('textarea[name="outtext"]')).toHaveValue('RGllcyBpc3QgZWluIGJlaXNwaWVsaGFmdGVyIHNjaMO2bmVyIFRlc3R0ZXh0Lg==');
  await page.locator('#nx-dropdown-rendered-2').click();
  await page.getByText('AES').click();
  await page.locator('#nx-dropdown-rendered-14').click();
  await page.getByText('plain chars').click();
  await page.locator('textarea[name="key"]').click();
  await page.locator('textarea[name="key"]').fill('sdfasdfr34534857idkdkdjccvn654235fsdfsdfkööpüejkdf');
  await page.getByRole('button', { name: 'Encrypt Text' }).click();
  await expect(page.locator('textarea[name="outtext"]')).toHaveValue(/.*[.].*[.].*/);
  await page.locator('#nx-dropdown-rendered-2').click();
  await page.getByText('SHA256', { exact: true }).click();
  await page.getByRole('button', { name: 'Hash Text' }).click();
  await expect(page.locator('textarea[name="outtext"]')).toHaveValue('wsoKINJo9B27qvsbd7N/FsJWdhEpXHLkOUBzdDSn/kA=');
  await page.getByLabel('encryption/hash', { exact: true }).locator('svg').click();
  await page.getByText('HmacSHA256').click();
  await page.getByRole('button', { name: 'Hash Text' }).click();
  await expect(page.locator('textarea[name="outtext"]')).toHaveValue('Dt/o3ZHP3vpq8FngXB6o2Qnzuq1UL1rLLV+w0W4vHUA=');
  await page.getByLabel('encryption/hash', { exact: true }).locator('svg').click();
  await page.getByText('AES').click();
  await page.getByRole('button', { name: 'Encrypt Text' }).click();
  await page.locator('textarea[name="outtext"]').click();
  await page.locator('textarea[name="outtext"]').click();
  await page.locator('textarea[name="outtext"]').press('ControlOrMeta+a');
  await page.locator('textarea[name="outtext"]').press('ControlOrMeta+c');
  await page.locator('textarea[name="inptxt"]').click();
  await page.locator('textarea[name="inptxt"]').press('Shift+Home');
  await page.locator('textarea[name="inptxt"]').fill('d+exAIMOQno=.RUwDF49BP4rbPR4D7Utyaw==.BFcUwgP6iMlVkLO/XDPid+ET6puENVAOGWNhIEFRlZxg6BqgIblzhe2gKkqztcX6');
  await page.locator('#nx-dropdown-rendered-0').click();
  await page.locator('#nx-dropdown-item-3').getByText('Base64').click();
  await page.locator('#nx-dropdown-rendered-4').click();
  await page.getByText('Utf8').click();
  await page.getByRole('button', { name: 'Decrypt Text' }).click();
  await expect(page.locator('textarea[name="outtext"]')).toHaveValue('Dies ist ein beispielhafter schöner Testtext.');
});