name: Angular Frontend Test

on:
  pull_request:
    types: [opened, synchronize, reopened]  

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          github-server-url: 'http://localhost:3000'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16'

      - name: Install dependencies
        run: |
          npm install
          npm ci
          npx playwright install

      - name: tests
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          openapi-generator-cli generate -i ./openapi.yaml  -g typescript-angular -o src/kryptutil-api-out
          xvfb-run npm run test 
          RC1=$?
          npx playwright test --quiet --reporter null
          RC2=$?
          
          if [ $(( RC1+RC2 )) -gt 0 ]
          then
           curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" \
             https://www.gdoeppert.de/mygitea/repos/${{github.action_repository}}/statuses/${{github.sha}} \
             -d '{"state":"failure","target_url":"https://gdlinux/build/status","description":"A test failed!","context":"continuous-integration/testpr"}'
          else
           curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" \
             https://www.gdoeppert.de/mygitea/repos/${{github.action_repository}}/statuses/${{github.sha}} \
             -d '{"state":"success","target_url":"https://gdlinux/build/status","description":"The build succeeded!","context":"continuous-integration/testpr"}'
          fi          
